apiVersion: v1
kind: Secret
metadata:
  name: homebox-mail-secret
  namespace: homebox
type: Opaque
data:
  mail-user: <base64-mail-user> # Encode your mail-user with `echo -n 'your-mail-user' | base64` and replace
  mail-password: <base64-mail-password> # Encode your mail password with `echo -n 'your-mail-password' | base64` and replace
  mail-from: <base64-mail-from> # Encode your mail from with `echo -n 'your-mail-from' | base64` and replace
