apiVersion: v1
kind: Secret
metadata:
  name: homebox-oidc-secret
  namespace: homebox
type: Opaque
data:
  hbox-client-id: eW91ci1jbGllbnQtaWQ= # Encode your client id with `echo -n 'your-client-id' | base64` and replace
  hbox-client-secret: eW91ci1jbGllbnQtc2VjcmV0 # Encode your client id with `echo -n 'your-client-secret' | base64` and replace