apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-sso-secret
  namespace: vaultwarden # Change to your specific namespace for vaultwarden
type: Opaque
data:
  SSO_CLIENT_ID: <client-id-base64-encoded> # Encode with `echo -n 'your-client-id' | base64`
  SSO_CLIENT_SECRET: <client-secret-base64-encoded> # Encode with `echo -n 'your-client-secret' | base64`