replicaCount: 1
geoliteDatabaseURL: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=%s&suffix=tar.gz
timeZone: Etc/UTC
analyticsDisabled: false
maxmindLicenseKey: ""
encryptionKey: ""
host: ""
database:
  provider: sqlite
  connectionString: file:data/pocket-id.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 100%
    partition: 0
pocketID:
  image:
    repository: ghcr.io/pocket-id/pocket-id
    tag: v1.16.0
    pullPolicy: IfNotPresent
  resources: {}
  securityContext: {}
backup:
  image:
    repository: docker.io/litestream/litestream
    tag: 0.5.5
    pullPolicy: IfNotPresent
  resources: {}
  securityContext: {}
  logging:
    level: INFO
    type: text
    stderr: false
  monitorInterval: 1s
  checkpointInterval: 1m
  busyTimeout: 1s
  minCheckpointPageCount: 1000
  maxCheckpointPageCount: 10000
  secret:
    create: true
    name: ""
    accessKey: ""
    secretKey: ""
    replicas: []
config:
  create: true
  name: ""
  telemetry:
    tracingEnabled: false
    metricsEnabled: false
    otel: {}
  audit:
    localIPv6Ranges: ""
  ui:
    useDefaults: true
    settings:
      app:
        appName: Pocket ID
        sessionDuration: 60
        emailsVerified: false
        allowOwnAccountEdit: true
        disableAnimations: false
      smtp:
        host: ""
        port: ""
        from: ""
        user: ""
        password: ""
        tls: none
        skipCertVerify: false
      email:
        loginNotificationEnabled: false
        oneTimeAccessAsAdminEnabled: false
        oneTimeAccessAsUnauthenticatedEnabled: false
      ldap:
        enabled: false
        url: ""
        bindDN: ""
        bindPassword: ""
        base: ""
        userSearchFilter: (objectClass=person)
        userGroupSearchFilter: (objectClass=groupOfNames)
        skipCertVerify: false
        attributes:
          user:
            uniqueIdentifier: ""
            username: ""
            email: ""
            firstName: ""
            lastName: ""
            profilePicture: ""
          group:
            member: member
            uniqueIdentifier: ""
            name: ""
            adminGroup: ""
secret:
  create: true
  name: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  annotations: {}
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http
startupProbe:
  httpGet:
    path: /healthz
    port: http
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
persistence:
  data:
    enabled: false
    existingClaim: ""
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    annotations: {}
ingress:
  enabled: false
  className: ""
  annotations: {}
  host: pocket-id.example.local
  paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
pockedID:
  image:
    tag: v2.2.0
