apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homebox.fullname" . }}
  labels:
    {{- include "homebox.labels" . | nindent 4 }}
stringData:
  # DATABASE
  {{- if eq .Values.env.HBOX_DATABASE_DRIVER "postgres" }}
  HBOX_DATABASE_DRIVER: "postgres"
    {{- if .Values.postgresql.enabled }}
  HBOX_DATABASE_HOST: {{ printf "%s-postgresql.%s.svc" .Release.Name .Release.Namespace | quote }}
  HBOX_DATABASE_PORT: "5432"
  HBOX_DATABASE_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  HBOX_DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  HBOX_DATABASE_DATABASE: {{ .Values.postgresql.auth.database | quote }}
    {{- else }}
  HBOX_DATABASE_HOST: {{ .Values.externalPostgresql.host | quote }}
  HBOX_DATABASE_PORT: {{ .Values.externalPostgresql.port | quote }}
  {{- if and .Values.externalPostgresql.auth.username (kindIs "string" .Values.externalPostgresql.auth.username) }}
  HBOX_DATABASE_USERNAME: {{ .Values.externalPostgresql.auth.username | quote }}
  {{- end }}
  {{- if and .Values.externalPostgresql.auth.password (kindIs "string" .Values.externalPostgresql.auth.password) }}
  HBOX_DATABASE_PASSWORD: {{ .Values.externalPostgresql.auth.password | quote }}
  {{- end }}
  {{- if and .Values.externalPostgresql.auth.database (kindIs "string" .Values.externalPostgresql.auth.database) }}
  HBOX_DATABASE_DATABASE: {{ .Values.externalPostgresql.auth.database | quote }}
  {{- end }}
    {{- end }}
  {{- else }}
  HBOX_DATABASE_DRIVER: "sqlite3"
  HBOX_DATABASE_SQLITE_PATH: {{ .Values.env.HBOX_DATABASE_SQLITE_PATH | quote }}
  {{- end }}
  HBOX_DATABASE_SSL_MODE: {{ .Values.env.HBOX_DATABASE_SSL_MODE | quote }}

  # VARIOUS
  {{- range $k, $v := .Values.env }}
    {{- if not (hasPrefix "HBOX_DATABASE" $k) }}
  {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}

