apiVersion: v2
name: vaultwarden
description: vaultwarden is an unofficial Bitwarden-compatible server written in Rust
type: application
keywords:
- Rust
- vaultwarden
sources:
- https://github.com/manulix3d/charts/tree/main/charts/vaultwarden
- https://github.com/dani-garcia/vaultwarden
appVersion: 1.35.2
maintainers:
- name: manulix3d
  email: manulix3d@manulix3d.de
  url: https://charts.manulix3d.de
version: 0.35.9
icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/refs/heads/main/resources/vaultwarden-icon.svg
kubeVersion: ">=1.12.0-0"
